export const GET_INSTITUTION_DATA = "GET_INSTITUTION_DATA";
export const SET_INSTITUTIONS = "SET_INSTITUTIONS";
export const CLEAN_INSTITUTION_DATA = "CLEAN_INSTITUTION_DATA";
export const SET_INSTITUTION_FILTERED = "SET_INSTITUTION_FILTERED";