export const GET_CARRER_DATA = "GET_CARRER_DATA";
export const SET_CARRERS = "SET_CARRERS";
export const CLEAN_CARRER_DATA = "CLEAN_CARRER_DATA";
export const SET_CARRERS_FILTERED = "SET_CARRERS_FILTERED";