export const GET_UNIVERSITY_DATA = "GET_UNIVERSITY_DATA";
export const SET_UNIVERSITIES = "SET_UNIVERSITIES";
export const CLEAN_UNIVERSITY_DATA = "CLEAN_UNIVERSITY_DATA";
export const SET_UNIVERSITIES_FILTERED = "SET_UNIVERSITIES_FILTERED";